// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Common/AppHeader.vue')['default']
    Avatars: typeof import('./src/components/Profile/Avatars.vue')['default']
    Avatars2Slider: typeof import('./src/components/Chat/UserProfile/avatars2Slider.vue')['default']
    AvatarsSlider: typeof import('./src/components/Feed/avatarsSlider.vue')['default']
    Button: typeof import('./src/components/Auth/Button.vue')['default']
    ContactsList: typeof import('./src/components/Chat/ContactsList/ContactsList.vue')['default']
    Conversation: typeof import('./src/components/Chat/Conversation/Conversation.vue')['default']
    copy: typeof import('./src/components/avatarsSlider copy.vue')['default']
    EmailSent: typeof import('./src/components/Auth/EmailSent.vue')['default']
    Form: typeof import('./src/components/Auth/Form.vue')['default']
    Header: typeof import('./src/components/Common/Header.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    InputField: typeof import('./src/components/Auth/InputField.vue')['default']
    Message: typeof import('./src/components/Chat/Conversation/Message.vue')['default']
    MessagesList: typeof import('./src/components/Chat/Conversation/MessagesList.vue')['default']
    Profile2Card: typeof import('./src/components/Chat/UserProfile/Profile2Card.vue')['default']
    ProfileCard: typeof import('./src/components/Feed/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchContacts: typeof import('./src/components/Chat/ContactsList/searchContacts.vue')['default']
    Select: typeof import('./src/components/Common/Select.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    TextArea: typeof import('./src/components/Common/TextArea.vue')['default']
    UserProfile: typeof import('./src/components/Chat/UserProfile/UserProfile.vue')['default']
  }
}
